all_nccl_gdr_off:
  collectives: [all]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [float]
  ENV_VARS:
    - id: NCCL_GDRCOPY_ENABLE
      value: 0
    - id: NCCL_GDRCOPY_FLUSH_ENABLE
      value: 0
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1
all_nccl_gdr_on:
  collectives: [all]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [float]
  ENV_VARS:
    - id: NCCL_GDRCOPY_ENABLE
      value: 1
    - id: NCCL_GDRCOPY_FLUSH_ENABLE
      value: 1
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1    
