all_nccl_gdr_off:
  collectives: [all]
  start_size: 1024
  end_size: 1024
  iterations: 2
  operation: [all]
  step_details:
    - type: multiple
      value: 2
  datatypes: [float, bfloat16]
  ENV_VARS:
    - id: NCCL_GDRCOPY_ENABLE
      value: 0
all_nccl_gdr_on:
  collectives: [all]
  start_size: 1024
  end_size: 1024
  iterations: 2
  operation: [all]
  step_details:
    - type: multiple
      value: 2
  datatypes: [float, bfloat16]
  ENV_VARS:
    - id: NCCL_GDRCOPY_ENABLE
      value: 1
