nccl_nchannels_per_peer_test_1:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 1
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_2:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 2
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_4:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 4
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_8:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 8
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_16:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 16
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_32:
  collectives: ["all_gather", "all_reduce", "alltoall", "alltoallv", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 32
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  








nccl_nchannels_per_peer_test_64:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 64
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_128:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 128
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_1024:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 1024
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  






nccl_nchannels_per_peer_test_3:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 3
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_5:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 5
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_6:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 6
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_7:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 7
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_9:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 9
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_10:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 10
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_11:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 11
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_12:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 12
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_15:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 15
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  
nccl_nchannels_per_peer_test_1023:
  collectives: ["all_gather", "all_reduce", "alltoall", "scatter","broadcast", "gather", "reduce", "reduce_scatter", "sendrecv"]
  start_size: 1
  end_size: 16g
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [all]
  ENV_VARS:
    - id: NCCL_NCHANNELS_PER_PEER
      value: 1023
    - id: HSA_NO_SCRATCH_RECLAIM
      value: 1  