single_test:
  collectives: [sendrecv]
  start_size: 1g
  end_size: 1GB
  iterations: 2
  operation: [sum]
  step_details:
    - type: multiple
      value: 2
  datatypes: [float]
  ENV_VARS:
    - id: NCCL_GDRCOPY_ENABLE
      value: 0
